import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage, LegalSection, LegalCallout } from "@/components/legal/LegalPage";
import {
  ARBITRATION_CARVE_OUTS,
  LEGAL_CONTACTS,
  LEGAL_ENTITY,
  LEGAL_JURISDICTION,
} from "@/lib/legal/constants";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "Terms of Service for the OASIS Agent Command Center, including AI output disclaimers, binding arbitration, class action waiver, and DMCA policy.",
};

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      subtitle={`The agreement between you and ${LEGAL_ENTITY} for use of the OASIS Agent Command Center.`}
    >
      <LegalSection n={1} title="Agreement">
        <p>
          By creating an account, submitting a form, or otherwise using the OASIS
          Agent Command Center (the &ldquo;Service&rdquo;), you agree to these
          Terms. If you are using the Service on behalf of an organisation, you
          represent that you have authority to bind that organisation.
        </p>
      </LegalSection>

      <LegalSection n={2} title="The Service is AI-powered">
        <p>
          The Service uses artificial intelligence, automated algorithms, and
          large language models to process data, generate content, classify
          messages, and execute workflows. AI output can be wrong, incomplete, or
          fabricated.
        </p>
        <LegalCallout>
          Output generated by the Service is not professional advice. It is not
          legal, financial, tax, accounting, medical, or underwriting advice, and
          must not be relied on as the sole basis for any decision. You are
          responsible for reviewing AI-generated content before you send, publish,
          file, or act on it.
        </LegalCallout>
        <p>
          Where the Service drafts or sends communications on your behalf, you
          remain the sender of record and are responsible for compliance with
          applicable anti-spam law, including CASL and CAN-SPAM.
        </p>
      </LegalSection>

      <LegalSection n={3} title="Your account and acceptable use">
        <p>You are responsible for activity under your account. You agree not to:</p>
        <ul>
          <li>Use the Service in violation of any law or third-party right.</li>
          <li>
            Upload content you do not have the right to upload, or use the Service
            to infringe copyright (see section 8).
          </li>
          <li>
            Attempt to extract model weights, circumvent rate limits, or use the
            Service to build a competing model.
          </li>
          <li>
            Submit another person&rsquo;s sensitive personal information without a
            lawful basis for doing so.
          </li>
        </ul>
      </LegalSection>

      <LegalSection n={4} title="Your content">
        <p>
          You retain ownership of the data and documents you submit. You grant us
          a limited, non-exclusive licence to host, process, and transmit that
          content solely to operate the Service for you — including transmission
          to the AI subprocessors listed in our{" "}
          <Link href="/privacy">Privacy Policy</Link>.
        </p>
      </LegalSection>

      <LegalSection n={5} title="Fees">
        <p>
          Paid plans are billed in advance. Fees are non-refundable except where
          required by law. We may change pricing on 30 days&rsquo; notice to the
          email on your account.
        </p>
      </LegalSection>

      <LegalSection n={6} title="Disclaimer and limitation of liability">
        <p>
          THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS
          AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED,
          INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
          NON-INFRINGEMENT.
        </p>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, OUR TOTAL AGGREGATE LIABILITY
          ARISING OUT OF OR RELATING TO THESE TERMS WILL NOT EXCEED THE GREATER OF
          (A) THE AMOUNT YOU PAID US IN THE TWELVE MONTHS BEFORE THE EVENT GIVING
          RISE TO THE CLAIM, OR (B) ONE HUNDRED DOLLARS ($100). WE WILL NOT BE
          LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE
          DAMAGES.
        </p>
        <p>
          Nothing in these Terms limits liability that cannot be limited by law,
          including liability for fraud, or for bodily or moral injury.
        </p>
      </LegalSection>

      <LegalSection n={7} title="Binding arbitration and class action waiver">
        <LegalCallout>
          <strong>
            BINDING ARBITRATION AND CLASS ACTION WAIVER: YOU AGREE THAT ALL
            DISPUTES BETWEEN YOU AND US WILL BE RESOLVED BY BINDING, INDIVIDUAL
            ARBITRATION UNDER THE AMERICAN ARBITRATION ASSOCIATION RULES. YOU
            EXPRESSLY WAIVE YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR
            CLASS-WIDE ARBITRATION.
          </strong>
        </LegalCallout>

        <h3>7.1 Scope and carve-outs</h3>
        <p>
          The clause above applies only to the extent permitted by applicable law.
          It does <strong>not</strong> apply, and you keep every right you would
          otherwise have to bring or join a court proceeding or class action, if
          you are a consumer in any of the following:
        </p>
        <ul>
          {ARBITRATION_CARVE_OUTS.map((c) => (
            <li key={c}>{c}</li>
          ))}
        </ul>
        <p>
          If you are a consumer resident in Quebec, section 11.1 of the Quebec{" "}
          <em>Consumer Protection Act</em> makes a pre-dispute arbitration clause
          and a class-action waiver unenforceable against you, and nothing in this
          section limits your right to bring proceedings before the courts of
          Quebec.
        </p>

        <h3>7.2 Exceptions that always survive</h3>
        <ul>
          <li>Either party may bring an individual claim in small claims court.</li>
          <li>
            Either party may seek injunctive relief in court for infringement or
            misuse of intellectual property.
          </li>
          <li>
            You may opt out of arbitration by emailing{" "}
            <a href={`mailto:${LEGAL_CONTACTS.legal}`}>{LEGAL_CONTACTS.legal}</a>{" "}
            within 30 days of first accepting these Terms. Opting out does not
            affect any other part of these Terms.
          </li>
        </ul>

        <h3>7.3 Severability of this section</h3>
        <p>
          If the class-action waiver is found unenforceable as to a particular
          claim, that claim will be severed and heard in court, and the remainder
          of this section will continue to apply to all other claims.
        </p>
      </LegalSection>

      <LegalSection n={8} title="Copyright and DMCA policy">
        <p>
          We respect intellectual property rights and will respond to properly
          submitted notices of alleged infringement concerning content stored on
          the Service at the direction of a user.
        </p>

        <h3>8.1 Submitting a notice</h3>
        <p>
          Send a notice to our designated agent at{" "}
          <a href={`mailto:${LEGAL_CONTACTS.dmca}`}>{LEGAL_CONTACTS.dmca}</a>, or
          use the form at <Link href="/dmca">oasisai.work/dmca</Link>. To be
          effective under 17 U.S.C. § 512(c)(3), a notice must include:
        </p>
        <ol>
          <li>
            A physical or electronic signature of the copyright owner or a person
            authorised to act on their behalf.
          </li>
          <li>Identification of the copyrighted work claimed to be infringed.</li>
          <li>
            Identification of the material claimed to be infringing, with enough
            detail for us to locate it.
          </li>
          <li>Your contact information.</li>
          <li>
            A statement that you have a good faith belief the use is not
            authorised by the copyright owner, its agent, or the law.
          </li>
          <li>
            A statement, under penalty of perjury, that the information is
            accurate and you are authorised to act on the owner&rsquo;s behalf.
          </li>
        </ol>

        <h3>8.2 Counter-notice and repeat infringers</h3>
        <p>
          If your content was removed, you may submit a counter-notice under 17
          U.S.C. § 512(g). We may restore the material 10 to 14 business days
          after forwarding a valid counter-notice unless the complainant files a
          court action. We terminate the accounts of repeat infringers in
          appropriate circumstances.
        </p>

        <h3>8.3 Canadian notice-and-notice</h3>
        <p>
          Because we operate from Canada, notices concerning Canadian users are
          also handled under the notice-and-notice regime in sections 41.25 to
          41.27 of the <em>Copyright Act</em> (Canada), under which we forward
          compliant notices to the relevant user rather than removing content
          automatically.
        </p>
        <p>
          Knowingly making a material misrepresentation in a notice may make you
          liable for damages under 17 U.S.C. § 512(f).
        </p>
      </LegalSection>

      <LegalSection n={9} title="Termination">
        <p>
          You may stop using the Service at any time. We may suspend or terminate
          access for breach of these Terms, non-payment, or where required by law.
          On termination you may request an export of your data within 30 days.
        </p>
      </LegalSection>

      <LegalSection n={10} title="Governing law and general terms">
        <p>
          These Terms are governed by the laws of the {LEGAL_JURISDICTION}, without
          regard to conflict-of-law rules, except where mandatory consumer law in
          your place of residence provides otherwise. If any provision is held
          unenforceable, the rest remains in effect.
        </p>
        <p>
          Questions:{" "}
          <a href={`mailto:${LEGAL_CONTACTS.legal}`}>{LEGAL_CONTACTS.legal}</a>.
        </p>
        <LegalCallout>
          These Terms are a working draft prepared from the product&rsquo;s actual
          behaviour on 2026-07-27. They have not been reviewed by counsel.
          Enforceability of the arbitration section in particular varies by
          jurisdiction and should be confirmed before it is relied on.
        </LegalCallout>
      </LegalSection>
    </LegalPage>
  );
}
