/**
 * GET /api/integrations/slack/app - what this workspace creates in its own
 * Slack, for the Slack drawer (components/os/connections/SlackOwnAppPanel.tsx):
 * the redirect URL, the two Request URLs carrying this workspace's id, the bot
 * scopes and events, and the same as one Slack app manifest. All generated by
 * lib/slack/own-app-setup.ts on OASIS's own origin (appOrigin, the origin the
 * install sends Slack as redirect_uri), never from a request header.
 *
 * Also says whether this workspace's own app is saved ("saved", "incomplete",
 * "none", "unreadable") and whether a saved app can be installed on this
 * deployment at all. No credential value is ever in the response.
 *
 * Owner/admin only (the Connections gate); the workspace is the session's.
 * OASIS's own workspace is refused (409): it uses OASIS's Slack app and has no
 * app of its own (lib/slack/own-app.ts slackAppKindFor), so Request URLs made
 * for it here would never be accepted.
 */
import { NextResponse } from "next/server";
import { resolveConnectionsActor, routeFailure } from "@/lib/connections/route-helpers";
import { appOrigin } from "@/lib/connections/popup";
import { slackOwnAppSetup } from "@/lib/slack/own-app-setup";
import { readSlackOwnApp, slackAppKindFor, slackInstallsPossible } from "@/lib/slack/own-app";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const json = (status: number, body: Record<string, unknown>) =>
  NextResponse.json(body, { status, headers: { "cache-control": "no-store" } });

export async function GET() {
  try {
    const resolved = await resolveConnectionsActor();
    if (!resolved.ok) return resolved.response;
    if (slackAppKindFor(resolved.actor.tenantId) === "oasis") {
      return json(409, {
        ok: false,
        error: "oasis_workspace_uses_oasis_app",
        message: "This workspace uses the OASIS Slack app, so it has no Slack app of its own to set up.",
      });
    }
    let origin: string;
    try {
      origin = appOrigin();
    } catch (err) {
      console.error("[integrations.slack.app] PUBLIC_APP_URL is not set", err instanceof Error ? err.message : err);
      return json(500, { ok: false, error: "app_url_missing" });
    }
    const setup = slackOwnAppSetup(origin, resolved.actor.tenantId);
    const own = await readSlackOwnApp(resolved.actor.tenantId);
    return json(200, {
      ok: true,
      redirect_url: setup.redirectUrl,
      events_url: setup.eventsUrl,
      interactivity_url: setup.interactivityUrl,
      bot_scopes: setup.botScopes,
      bot_events: setup.botEvents,
      manifest: setup.manifest,
      app: own.state,
      installs_possible: slackInstallsPossible(),
    });
  } catch (error) {
    return routeFailure("api/integrations/slack/app GET", error);
  }
}
