/**
 * POST /api/applications/[id]/match-lenders — rank tenant lenders by
 * fit against this application's underwriting data.
 *
 * Phase 10.3 of SunBiz CRM. The Application detail page renders the
 * top results as a "Recommended Lenders" card so the operator can
 * shop the deal to the strongest fits in one click instead of
 * eyeballing every lender's requirements row-by-row.
 *
 * Scoring is rule-based, not LLM-based:
 *   - Each lender carries fields min_monthly_revenue, max_funded_amount,
 *     min_time_in_business_months, fico_floor, product_types[].
 *   - We compare each against the application data (or its
 *     underwriting_jsonb summary, populated by Phase 7's underwrite
 *     chain). Pass = the application meets/exceeds the requirement.
 *   - Score = passes / total_checks. Ties broken by max_funded_amount
 *     descending (bigger lenders win on equal fit).
 *
 * Why not LLM-narrative scoring: rule-based is faster, deterministic,
 * and the operator can reason about WHY a lender ranks high. The
 * narrative prose is now generated by buildLenderNarrative() and
 * added to every ranked entry in the response (2026-05-25).
 *
 * Response:
 *   { ok, application_summary: {...}, ranked: [{ lender_id, name, score,
 *     checks, reasons, warnings, blockers, narrative }] }
 */

import { NextRequest, NextResponse } from "next/server";
import { getSessionUser, getServiceSupabase } from "@/lib/supabase-server";
import { scoreLenderMatch, complianceProfileInputs } from "@/lib/lenders/match-fitness";
import { applyLenderIntelligenceBias } from "@/lib/lenders/lender-intelligence";
import { buildLenderNarrative } from "@/lib/lenders/match-narrative";
import type { LenderProfile, ApplicationProfile } from "@/lib/lenders/match-fitness";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type LenderData = {
  id: string;
  name?: string;
  min_monthly_revenue?: number;
  max_funded_amount?: number;
  min_time_in_business_months?: number;
  fico_floor?: number;
  sla_response_days?: number;
  product_types?: string[] | string;
  // SOP §1 shop_list filter fields (2026-05-31).
  tier?: "A" | "B" | "C" | "D" | "Micro";
  paper_grades?: string[];
  position_min?: number;
  position_max?: number;
  defaults_policy?: "none" | "satisfied_only" | "accepts";
  max_negative_days?: number;
  reverses_only?: boolean;
};

type CheckResult = {
  key: string;
  label: string;
  requirement: string;
  actual: string;
  passed: boolean;
};

type Ranked = {
  lender_id: string;
  name: string;
  score: number;
  passes: number;
  checks: CheckResult[];
};

function num(v: unknown): number | null {
  if (typeof v === "number" && Number.isFinite(v)) return v;
  if (typeof v === "string") {
    const n = Number(v.replace(/[^0-9.-]+/g, ""));
    return Number.isNaN(n) ? null : n;
  }
  return null;
}

export async function POST(
  _req: NextRequest,
  ctx: { params: Promise<{ id: string }> },
) {
  const user = await getSessionUser();
  if (!user) return NextResponse.json({ ok: false, error: "unauthorized" }, { status: 401 });
  const db = getServiceSupabase();
  const profileRes = await db
    .from("user_profiles")
    .select("tenant_id")
    .eq("auth_user_id", user.id)
    .maybeSingle();
  const tenantId = (profileRes.data as { tenant_id: string | null } | null)?.tenant_id ?? null;
  if (!tenantId) return NextResponse.json({ ok: false, error: "no_tenant" }, { status: 401 });

  const { id: applicationId } = await ctx.params;

  // Pull the application row.
  const appRow = await db
    .from("tenant_records")
    .select("id, data")
    .eq("tenant_id", tenantId)
    .eq("entity_type", "application")
    .eq("id", applicationId)
    .maybeSingle();
  if (appRow.error || !appRow.data) {
    return NextResponse.json({ ok: false, error: "application_not_found" }, { status: 404 });
  }
  const appData = (appRow.data as { data: Record<string, unknown> }).data || {};

  // Resolve the underwriting summary. Prefer the Phase 7 underwrite
  // chain's output if present; fall back to whatever's on the
  // application row directly (operator-entered fields).
  const underwriting = (appData.underwriting_jsonb || appData.underwriting || {}) as Record<string, unknown>;
  const monthlyRevenue =
    num(underwriting.monthly_revenue) ??
    num(underwriting.avg_monthly_deposits) ??
    num(appData.monthly_revenue);
  const requestedAmount =
    num(appData.requested_amount) ??
    num(appData.amount) ??
    num(underwriting.requested_amount);
  const timeInBusinessMonths =
    num(appData.time_in_business_months) ??
    num(appData.business_age_months) ??
    num(underwriting.time_in_business_months);
  const ficoScore =
    num(appData.fico) ??
    num(appData.fico_score) ??
    num(underwriting.fico);
  const productType =
    typeof appData.product_type === "string"
      ? (appData.product_type as string).toLowerCase()
      : typeof underwriting.product_type === "string"
        ? (underwriting.product_type as string).toLowerCase()
        : null;

  // SOP §1 fields the underwriter chain populates. Same fall-through
  // pattern: app row first, then underwriting summary. Undefined when
  // not yet computed — the scorer treats absence as info, not failure.
  const paperGrade =
    typeof appData.paper_grade === "string"
      ? (appData.paper_grade as string).toUpperCase()
      : typeof underwriting.paper_grade === "string"
        ? (underwriting.paper_grade as string).toUpperCase()
        : null;
  const positionCount =
    num(appData.position_count) ??
    num(underwriting.position_count) ??
    num(underwriting.active_positions);
  const hasDefault =
    typeof appData.has_default === "boolean"
      ? (appData.has_default as boolean)
      : typeof underwriting.has_default === "boolean"
        ? (underwriting.has_default as boolean)
        : null;
  const defaultSatisfied =
    typeof appData.default_satisfied === "boolean"
      ? (appData.default_satisfied as boolean)
      : typeof underwriting.default_satisfied === "boolean"
        ? (underwriting.default_satisfied as boolean)
        : null;
  const negativeDays =
    num(appData.negative_days) ??
    num(underwriting.negative_days) ??
    num(underwriting.worst_month_negative_days);
  const dealKind =
    appData.deal_kind === "reverse_consolidation" || appData.deal_kind === "fresh_capital"
      ? (appData.deal_kind as "reverse_consolidation" | "fresh_capital")
      : null;

  // Pull every lender for this tenant. Tenants typically have <50
  // lenders so we score in-memory.
  const lendersRes = await db
    .from("tenant_records")
    .select("id, data")
    .eq("tenant_id", tenantId)
    .eq("entity_type", "lender");
  if (lendersRes.error) {
    return NextResponse.json(
      { ok: false, error: "lenders_lookup_failed", detail: lendersRes.error.message },
      { status: 500 },
    );
  }

  // Build the ApplicationProfile shape needed by match-fitness + narrative.
  const applicationProfile: ApplicationProfile = {
    id: applicationId,
    monthly_revenue: monthlyRevenue ?? undefined,
    time_in_business_months: timeInBusinessMonths ?? undefined,
    applicant_fico: ficoScore ?? undefined,
    requested_amount: requestedAmount ?? undefined,
    desired_product: productType ?? undefined,
    paper_grade: paperGrade ?? undefined,
    position_count: positionCount ?? undefined,
    has_default: hasDefault ?? undefined,
    default_satisfied: defaultSatisfied ?? undefined,
    negative_days: negativeDays ?? undefined,
    deal_kind: dealKind ?? undefined,
    // merchant_state + industry via the shared resolver (same mapping every
    // scoring path uses) so the preview reflects the restricted-lender gates.
    ...complianceProfileInputs(appData),
  };

  // Build a lookup of raw lender data for LenderProfile construction later.
  const lenderDataMap = new Map<string, LenderData>();
  for (const r of lendersRes.data || []) {
    const d = ((r as { data: Record<string, unknown> }).data || {}) as LenderData;
    lenderDataMap.set(r.id, d);
  }

  const ranked: Ranked[] = (lendersRes.data || []).map((r) => {
    const data = ((r as { data: Record<string, unknown> }).data || {}) as LenderData;
    const checks: CheckResult[] = [];

    // Monthly revenue floor. If application doesn't have monthly
    // revenue, mark this check inconclusive (passed=false but with
    // 'unknown' actual) so the operator sees why the lender ranks low.
    if (typeof data.min_monthly_revenue === "number") {
      const passes = monthlyRevenue !== null && monthlyRevenue >= data.min_monthly_revenue;
      checks.push({
        key: "monthly_revenue",
        label: "Monthly revenue",
        requirement: `≥ $${data.min_monthly_revenue.toLocaleString()}`,
        actual: monthlyRevenue !== null ? `$${monthlyRevenue.toLocaleString()}` : "unknown",
        passed: passes,
      });
    }
    if (typeof data.max_funded_amount === "number" && requestedAmount !== null) {
      const passes = requestedAmount <= data.max_funded_amount;
      checks.push({
        key: "max_amount",
        label: "Funded amount",
        requirement: `≤ $${data.max_funded_amount.toLocaleString()}`,
        actual: `$${requestedAmount.toLocaleString()}`,
        passed: passes,
      });
    }
    if (typeof data.min_time_in_business_months === "number") {
      const passes =
        timeInBusinessMonths !== null && timeInBusinessMonths >= data.min_time_in_business_months;
      checks.push({
        key: "tib",
        label: "Time in business",
        requirement: `≥ ${data.min_time_in_business_months} months`,
        actual:
          timeInBusinessMonths !== null
            ? `${timeInBusinessMonths} months`
            : "unknown",
        passed: passes,
      });
    }
    if (typeof data.fico_floor === "number") {
      const passes = ficoScore !== null && ficoScore >= data.fico_floor;
      checks.push({
        key: "fico",
        label: "FICO",
        requirement: `≥ ${data.fico_floor}`,
        actual: ficoScore !== null ? `${ficoScore}` : "unknown",
        passed: passes,
      });
    }
    if (data.product_types && productType) {
      const allowed = Array.isArray(data.product_types)
        ? data.product_types
        : typeof data.product_types === "string"
          ? data.product_types.split(",").map((s) => s.trim())
          : [];
      const passes = allowed.length === 0 || allowed.includes(productType);
      checks.push({
        key: "product",
        label: "Product type",
        requirement: allowed.length === 0 ? "(any)" : allowed.join(", "),
        actual: productType,
        passed: passes,
      });
    }

    // SOP §1 hard-requirement checks. Each is gated on the lender
    // carrying the constraint AND the application carrying the matching
    // data point. When either is missing the check is skipped (mirrors
    // the original revenue / FICO / TIB pattern above).
    if (typeof data.position_min === "number" || typeof data.position_max === "number") {
      const min = typeof data.position_min === "number" ? data.position_min : 1;
      const max =
        typeof data.position_max === "number" && data.position_max > 0
          ? data.position_max
          : Number.POSITIVE_INFINITY;
      const maxLabel = max === Number.POSITIVE_INFINITY ? "any" : String(max);
      const passes =
        positionCount !== null && positionCount >= min && positionCount <= max;
      checks.push({
        key: "position",
        label: "Position",
        requirement: `${min}-${maxLabel}`,
        actual: positionCount !== null ? String(positionCount) : "unknown",
        passed: passes,
      });
    }
    if (Array.isArray(data.paper_grades) && data.paper_grades.length > 0) {
      const passes = paperGrade !== null && data.paper_grades.includes(paperGrade);
      checks.push({
        key: "paper_grade",
        label: "Paper grade",
        requirement: data.paper_grades.join("/"),
        actual: paperGrade ?? "unknown",
        passed: passes,
      });
    }
    if (data.defaults_policy && hasDefault !== null) {
      let passes = true;
      let actual = hasDefault ? "has default" : "no default";
      if (hasDefault) {
        if (data.defaults_policy === "none") {
          passes = false;
        } else if (data.defaults_policy === "satisfied_only") {
          passes = defaultSatisfied === true;
          actual = defaultSatisfied ? "satisfied default" : "unsatisfied default";
        }
      }
      checks.push({
        key: "defaults",
        label: "Defaults",
        requirement: data.defaults_policy,
        actual,
        passed: passes,
      });
    }
    if (typeof data.max_negative_days === "number" && negativeDays !== null) {
      const passes = negativeDays <= data.max_negative_days;
      checks.push({
        key: "negative_days",
        label: "Negative days",
        requirement: `≤ ${data.max_negative_days}`,
        actual: String(negativeDays),
        passed: passes,
      });
    }
    if (data.reverses_only) {
      const passes = dealKind === "reverse_consolidation";
      checks.push({
        key: "reverses_only",
        label: "Deal kind",
        requirement: "reverse_consolidation",
        actual: dealKind ?? "unknown",
        passed: passes,
      });
    }

    const passes = checks.filter((c) => c.passed).length;
    const total = checks.length;
    const score = total === 0 ? 0 : passes / total;

    return {
      lender_id: r.id,
      name: data.name || "(unnamed lender)",
      score,
      passes,
      checks,
    };
  });

  // Sort: score desc, then tiebreak by max_funded_amount desc (more
  // headroom is better when fit is equal).
  ranked.sort((a, b) => {
    if (a.score !== b.score) return b.score - a.score;
    const aMax = a.checks.find((c) => c.key === "max_amount");
    const bMax = b.checks.find((c) => c.key === "max_amount");
    const aN = aMax ? parseFloat(aMax.requirement.replace(/[^0-9.]/g, "")) : 0;
    const bN = bMax ? parseFloat(bMax.requirement.replace(/[^0-9.]/g, "")) : 0;
    return bN - aN;
  });

  const top = ranked.slice(0, 8);

  // ── Narrative + feedback-bias layer (2026-05-25) ─────────────────────────
  // Run scoreLenderMatch (0-100 int scale + reasons + warnings) for the
  // top-N so we have the full MatchScore shape needed by
  // buildLenderNarrative and applyLenderFeedbackBias. The existing
  // check-based scoring above is kept for backward compat (detail view
  // consumes `checks` directly).
  const topMatchPairs = top.map((r) => {
    const raw = lenderDataMap.get(r.lender_id);
    const lenderProfile: LenderProfile = {
      id: r.lender_id,
      name: raw?.name || r.name,
      product_types: raw?.product_types,
      min_monthly_revenue: raw?.min_monthly_revenue ?? undefined,
      max_funded_amount: raw?.max_funded_amount ?? undefined,
      min_time_in_business_months: raw?.min_time_in_business_months ?? undefined,
      fico_floor: raw?.fico_floor ?? undefined,
      sla_response_days: raw?.sla_response_days ?? undefined,
      tier: raw?.tier,
      paper_grades: raw?.paper_grades,
      position_min: raw?.position_min,
      position_max: raw?.position_max,
      defaults_policy: raw?.defaults_policy,
      max_negative_days: raw?.max_negative_days,
      reverses_only: raw?.reverses_only,
    };
    return { matchScore: scoreLenderMatch(lenderProfile, applicationProfile), lenderProfile };
  });

  // Bias by LEARNED lender behavior on similar paper (lender_reply_outcomes +
  // deal_paper_snapshot). Falls back to unmodified scores on empty history / DB error.
  const biasedMatchScores = await applyLenderIntelligenceBias(
    topMatchPairs.map((t) => t.matchScore),
    applicationProfile,
    tenantId,
  );

  // Build the enriched response — preserve existing fields, add
  // reasons / warnings / blockers / narrative from the biased match scores.
  const enriched = top.map((r, i) => {
    const biased = biasedMatchScores[i];
    const { lenderProfile } = topMatchPairs[i];
    return {
      ...r,
      reasons: biased.reasons,
      warnings: biased.warnings,
      blockers: biased.blockers,
      narrative: buildLenderNarrative(biased, lenderProfile, applicationProfile),
    };
  });

  return NextResponse.json({
    ok: true,
    application_summary: {
      monthly_revenue: monthlyRevenue,
      requested_amount: requestedAmount,
      time_in_business_months: timeInBusinessMonths,
      fico: ficoScore,
      product_type: productType,
    },
    ranked: enriched,
    total_lenders: ranked.length,
  });
}
