/**
 * A domain that is FOR SALE is not a website, and must never be a competitor.
 *
 * ═══ THE INCIDENT THIS PINS (2026-08-25) ═══════════════════════════════════
 *
 * Adon, looking at a live battle card for a Mississauga restaurant: two of the
 * three "best-scoring competitors" opened hugedomains.com, a page selling the
 * domain rather than a restaurant.
 *
 * The broken links were the symptom. The defect was the SCORE. Measured in the
 * corpus that day:
 *
 *   - 53 audits landed on a HugeDomains parking page
 *   - every single one scored EXACTLY 82
 *   - all 53 were in the top tier (>=74, the band that "beats our best site")
 *
 * The identical 82 is the tell. A parking page is one template, so it scores
 * once and repeats -- and it scores WELL, because it really is fast, HTTPS,
 * mobile-friendly, and carries a phone link, a form, testimonials and a logo.
 * The 49 checks did exactly what they were built to do, on a page belonging to
 * a domain broker.
 *
 * Competitor selection takes the BEST-scoring peers in a city and industry, so
 * an 82 outranked almost every real business: parking pages were not merely
 * included, they were PREFERENTIALLY surfaced. A rep would have said "their
 * site scores 82, yours scores 9" about a business with no website at all.
 * That is a false statement, to a prospect, in a rep's mouth, generated by us.
 */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { TursoQueryBuilder } from "@/lib/turso-postgrest";
import {
  isParkedUrl,
  isCrossDomainRedirect,
  baseDomain,
  finalUrlFromSignals,
  parkedSignalsOrFilter,
  confirmParked,
  PARKING_HOSTS,
  PARKING_PATH_MARKERS,
} from "../lib/web-leads/parked-domains";

const read = (p: string) => readFileSync(p, "utf8");

// ---------------------------------------------------------------------------
// 1. THE REAL URLS. Captured from the corpus, not invented.
// ---------------------------------------------------------------------------
assert.equal(
  isParkedUrl("https://www.hugedomains.com/domain_profile.cfm?d=ambianceofindia.com"),
  true,
  "the exact finalUrl stored for Ambiance of India must be recognised",
);
assert.equal(
  isParkedUrl("https://www.hugedomains.com/domain_profile.cfm?d=jingthai.com"),
  true,
  "the exact finalUrl stored for Jing Thai must be recognised",
);
// The third competitor on that same card was a REAL restaurant site and must
// survive. Over-matching here deletes real businesses from every peer group,
// which is the opposite failure and just as damaging to a percentile.
assert.equal(isParkedUrl("https://www.a1sweets.com/"), false, "a real site must not be flagged");

// A FIXED list, deliberately not derived from PARKING_HOSTS.
//
// The first version of this block was `for (const host of PARKING_HOSTS)
// assert(isParkedUrl(host))`, which is circular: it checks the list against
// itself, so deleting an entry just means one fewer case is tested and the
// suite stays green. Caught by mutating the module -- commenting out
// "hugedomains.com" produced no failure at all, which is the same
// asserts-presence-not-behaviour defect this repo has been bitten by before.
//
// These names are written out so that REMOVING one from the module fails here.
const MUST_DETECT = [
  "https://www.hugedomains.com/domain_profile.cfm?d=example.com",
  // Deliberately WITHOUT the `domain_profile.cfm` path. That path is its own
  // entry in PARKING_HOSTS, so every realistic HugeDomains URL matches twice --
  // which masked the host entry entirely: commenting out "hugedomains.com" left
  // the suite green because the path entry still caught it. This URL isolates
  // the host, so removing it now fails here.
  "https://www.hugedomains.com/",
  "https://www.afternic.com/domain/example.com",
  "https://sedo.com/search/details/?domain=example.com",
  "https://dan.com/buy-domain/example.com",
  "https://www.bodis.com/",
  "https://parkingcrew.net/example.com",
] as const;
for (const url of MUST_DETECT) {
  assert.equal(isParkedUrl(url), true, `${url} must be recognised as a parked domain`);
}
// Every host the module claims to cover is genuinely matched by the matcher --
// this one IS derived from the list on purpose, and it catches the opposite
// error: an entry added with a typo or a stray space that never matches.
for (const host of PARKING_HOSTS) {
  assert.equal(
    isParkedUrl(`https://${host}/whatever`),
    true,
    `${host} is listed in PARKING_HOSTS but isParkedUrl does not match it`,
  );
}

// ---------------------------------------------------------------------------
// 1b. 🚨 THE REGRESSION THAT NEARLY REWROTE REAL DATA (2026-08-25).
//
// The first version of isParkedUrl was `PARKING_HOSTS.some(h => url.includes(h))`.
// Caught while dry-running the corpus cleanup, one query BEFORE the write:
//
//   "Chez Jordan Corporation" — https://www.chezjordan.com/ — quality_score 55
//
// matched the entry `dan.com`, because "chezjor|dan.com" contains it. A real
// restaurant with a real website would have had its score stripped and been
// removed from every peer group — and a shrinking peer group moves the
// percentiles a rep quotes out loud. This is the exact failure the module
// header warns about, committed by the module itself.
//
// Host matching is now on a LABEL BOUNDARY: exact hostname, or a `.`-prefixed
// suffix. These names are the trap, written out so it cannot come back.
// ---------------------------------------------------------------------------
for (const realSite of [
  "https://www.chezjordan.com/",   // the one actually in the corpus
  "https://jordan.com/",
  "https://www.sudan.com/",
  "https://bogdan.com/menu",
  "https://mysedo.com/",           // not sedo.com
  "https://abovegroundpools.com/", // not above.com
  "https://dance.com/",
]) {
  assert.equal(
    isParkedUrl(realSite),
    false,
    `${realSite} is a real business and must NEVER be treated as parked — a substring match is what broke this`,
  );
}
// A genuine subdomain of a parking service still counts.
assert.equal(isParkedUrl("https://www.dan.com/buy"), true, "www.dan.com IS dan.com");
assert.equal(isParkedUrl("https://foo.sedo.com/x"), true, "a real subdomain still counts");

// And the SQL prefilter must never be used as the verdict, because LIKE cannot
// express a label boundary: the query WILL return chezjordan.com as a candidate.
{
  assert.match(
    parkedSignalsOrFilter(),
    /signals\.like\./,
    "the SQL filter is a coarse net over the signals blob",
  );
  const candidates = [
    { business_id: "real", signals: JSON.stringify({ finalUrl: "https://www.chezjordan.com/" }) },
    { business_id: "parked", signals: JSON.stringify({ finalUrl: "https://www.hugedomains.com/domain_profile.cfm?d=x" }) },
  ];
  const confirmed = confirmParked(candidates);
  assert.equal(confirmed.has("real"), false, "confirmParked must reject the SQL false positive");
  assert.equal(confirmed.has("parked"), true, "and keep the genuine one");
  assert.equal(confirmed.size, 1);

  // The score index must consume the query through confirmParked, not directly.
  const scores = read("lib/web-leads/scores.ts");
  assert.match(scores, /confirmParked\(parkedCandidates\)/, "the index must re-check candidates");
  assert.match(scores, /business_id,signals/, "which means it must select signals to re-check with");
}

// ---------------------------------------------------------------------------
// 2. FAILS CLOSED TOWARD KEEPING THE BUSINESS.
//
// A business is only ever dropped on POSITIVE evidence. Missing or unparseable
// data means "we do not know", which must never mean "delete it from the
// corpus" -- a silently shrinking peer group changes percentiles a rep quotes.
// ---------------------------------------------------------------------------
for (const junk of [null, undefined, "", "   ", 42, {}, []]) {
  assert.equal(isParkedUrl(junk as never), false, `${JSON.stringify(junk)} is not evidence of parking`);
}

// ---------------------------------------------------------------------------
// 3. REAL SITES THAT MUST SURVIVE.
//
// Every one of these redirects somewhere, and every one is a real business.
// ---------------------------------------------------------------------------
for (const real of [
  "https://www.a1sweets.com/",
  "https://example.ca/menu",
  "https://shop.myshopify.com/store",
  "https://www.facebook.com/somerestaurant",
  "https://sites.google.com/view/a-real-cafe",
  "https://a-real-business.squarespace.com",
]) {
  assert.equal(isParkedUrl(real), false, `${real} must NOT be treated as parked`);
}

// ---------------------------------------------------------------------------
// 4. baseDomain, which only ever compares two hosts to each other.
// ---------------------------------------------------------------------------
assert.equal(baseDomain("http://www.ambianceofindia.com"), "ambianceofindia.com");
assert.equal(baseDomain("https://WWW.Example.COM/path?q=1"), "example.com");
assert.equal(baseDomain("sub.deep.example.com"), "example.com");
assert.equal(baseDomain("example.com"), "example.com");
assert.equal(baseDomain(null), null);
assert.equal(baseDomain("not a url at all"), "not a url at all".split(".").slice(-2).join("."));

// ---------------------------------------------------------------------------
// 5. THE CROSS-DOMAIN RULE IS REPORTING ONLY, AND MUST STAY THAT WAY.
//
// It has high recall and mediocre precision: rebrands, franchises, Shopify and
// Wix storefronts and Facebook-only businesses ALL redirect cross-domain and
// are real websites. Acting on it alone would delete them.
// ---------------------------------------------------------------------------
assert.equal(
  isCrossDomainRedirect("http://www.ambianceofindia.com", "https://www.hugedomains.com/domain_profile.cfm?d=x"),
  true,
);
assert.equal(
  isCrossDomainRedirect("http://example.com", "https://www.example.com/"),
  false,
  "www and a scheme change are the SAME domain",
);
{
  // The guard that keeps rule 2 out of the acted-on path. If a future edit
  // wires isCrossDomainRedirect into the score index or the corpus, this fails
  // and whoever did it has to read the reasoning above first.
  const scores = read("lib/web-leads/scores.ts");
  const corpus = read("lib/web-leads/competitors.ts");
  assert.doesNotMatch(
    scores,
    /isCrossDomainRedirect/,
    "the cross-domain rule must NOT gate scoring -- rebrands, franchises and hosted storefronts are real sites",
  );
  assert.doesNotMatch(
    corpus,
    /isCrossDomainRedirect/,
    "the cross-domain rule must NOT gate the competitor corpus",
  );
}

// ---------------------------------------------------------------------------
// 6. finalUrl comes out of the stored signals blob, in both shapes the driver
//    hands back, and a malformed blob never takes down an index build.
// ---------------------------------------------------------------------------
assert.equal(
  finalUrlFromSignals('{"finalUrl":"https://www.hugedomains.com/domain_profile.cfm?d=x","status":200}'),
  "https://www.hugedomains.com/domain_profile.cfm?d=x",
);
assert.equal(finalUrlFromSignals({ finalUrl: "https://a.example" }), "https://a.example");
for (const junk of ["", "not json", "{broken", null, undefined, 42, {}, { finalUrl: 7 }]) {
  assert.equal(finalUrlFromSignals(junk), null, `${JSON.stringify(junk)} must yield null, never throw`);
}

// ---------------------------------------------------------------------------
// 7. THE SQL FILTER IS GENERATED FROM THE LIST.
//
// Hand-writing the query beside the list is how the two drift: a host added to
// PARKING_HOSTS but not to the filter is a parking page that keeps its 82 and
// goes back to being surfaced as a top competitor, with nothing on screen to
// suggest anything is wrong.
// ---------------------------------------------------------------------------
{
  const filter = parkedSignalsOrFilter();
  for (const host of PARKING_HOSTS) {
    assert.ok(filter.includes(host), `the generated SQL filter must cover ${host}`);
  }
  assert.match(filter, /^signals\.like\./, "must be a PostgREST-style or() filter over signals");

  const scores = read("lib/web-leads/scores.ts");
  assert.match(
    scores,
    /\.or\(parkedSignalsOrFilter\(\)\)/,
    "the score index must use the generated filter, not a hand-copied host list",
  );
}

// ---------------------------------------------------------------------------
// 7b. THE FILTER ACTUALLY COMPILES, AGAINST THE REAL ADAPTER.
//
// Not optional, and not theoretical. Our Turso bridge implements a SUBSET of
// PostgREST, and its `or()` grammar has crashed before on exactly this shape --
// a value containing dots. That bug lost public-form submissions for every
// merchant with a dotted email local part (tests/or-filter-dotted-values.test.ts).
//
// Every host in this list contains dots. If the parser chokes, the read throws,
// and because the read is fail-closed the ENTIRE leads page 500s -- every rep,
// every lead, not just the parked ones. Asserting the string looks right proves
// nothing about whether the database will accept it, so this runs the real
// TursoQueryBuilder and checks the SQL it produces.
// ---------------------------------------------------------------------------
{
  const qb = new TursoQueryBuilder(null as never, "leadgen_site_audits");
  qb.or(parkedSignalsOrFilter());
  const conds = (qb as unknown as { conds: { sql: string; args: unknown[] }[] }).conds;
  assert.equal(conds.length, 1, "or() must compile to exactly one grouped condition");

  const [c] = conds;
  // One LIKE per host, OR-joined, over the signals column.
  // Hosts AND path markers: the net has to cast over both lists, or a parking
  // page identified only by its path never becomes a candidate at all.
  assert.equal(
    c.args.length,
    PARKING_HOSTS.length + PARKING_PATH_MARKERS.length,
    "every host and path marker must become a bound parameter -- a missing one is a parking page that keeps its 82",
  );
  for (const host of [...PARKING_HOSTS, ...PARKING_PATH_MARKERS]) {
    assert.ok(
      c.args.includes(`%${host}%`),
      `${host} must reach the query as a bound LIKE parameter (dots intact, wildcards converted)`,
    );
  }
  // Bound parameters, never interpolated. `signals` is crawler-derived text
  // from 27,000 sites we do not control.
  assert.match(c.sql, /"signals" LIKE \?/, "hosts must be BOUND, never inlined into SQL");
  assert.doesNotMatch(c.sql, /hugedomains/, "no host may appear inline in the SQL string");
  assert.ok(c.sql.includes(" OR "), "the segments must be OR-joined");
}

// ---------------------------------------------------------------------------
// 8. PARKED OUTRANKS UNREACHABLE IN resolveScore's PRECEDENCE.
//
// We did not fail to reach a parked domain -- we reached it perfectly and got a
// broker's sales page. Reporting it as "we could not check this site" replaces
// one false statement with another, and throws away the best opener a rep has.
// ---------------------------------------------------------------------------
{
  const scores = read("lib/web-leads/scores.ts");
  const parkedAt = scores.indexOf('scoreState: "parked"');
  const unreachableAt = scores.indexOf('scoreState: "unreachable"');
  assert.ok(parkedAt > -1 && unreachableAt > -1, "both states must be resolved");
  assert.ok(
    parkedAt < unreachableAt,
    "the parked check must come BEFORE the unreachable check in resolveScore",
  );
  // And a parked business never reaches the scored map in the first place.
  assert.match(
    scores,
    /if \(parked\.has\((?:r|row)\.business_id\)\) continue;/,
    "parked businesses must be excluded where scores are BUILT, not filtered at each read site",
  );

  // FAILS CLOSED, like its three sibling reads.
  //
  // Added after mutating the module: deleting the error throw broke nothing,
  // which meant the fail-closed behaviour was real but unpinned. A parked read
  // that silently returned nothing would put every for-sale page straight back
  // into the peer groups at 82 and look completely normal on screen -- the
  // exact defect this whole file exists to prevent, reintroduced by a swallowed
  // error rather than by a wrong list.
  // Matches the RESULT BINDING by shape, not by name. e1d4063b (#318) moved
  // this read into its own memo, renaming `parkedRes` to `res`, and the
  // assertion below kept naming the old variable — so it failed on a pure
  // rename while the fail-loud behaviour it guards was still there. Anchoring
  // on `parked_index_read_failed` keeps the guard exact: deleting the throw, or
  // degrading it to `return []`, still fails here.
  assert.match(
    scores,
    /if \(\w+\.error\) throw new Error\(`parked_index_read_failed/,
    "the parked read must throw on error, never degrade to an empty set",
  );
  // And it must PROVE it read everything. Truncation here is the same failure
  // wearing a different hat: the parking pages beyond the cut keep their 82.
  assert.match(
    scores,
    /assertCompleteRead\("parked_index"/,
    "the parked read must prove completeness, like the three reads beside it",
  );
}

// ---------------------------------------------------------------------------
// 9. THE COMPETITOR CORPUS DROPS THEM TOO.
// ---------------------------------------------------------------------------
assert.match(
  read("lib/web-leads/competitors.ts"),
  /if \(scoreIndex\.parked\.has\(businessId\)\) continue;/,
  "the competitor corpus must drop parked businesses -- this is the module where the damage happened",
);

// ---------------------------------------------------------------------------
// 10. EVERY SURFACE SAYS IT OUT LOUD, AND NONE OF THEM SAYS A NUMBER.
// ---------------------------------------------------------------------------
for (const [file, needle] of [
  ["components/web-leads/useAudit.ts", /parked: "Their domain has lapsed and is listed for sale/],
  ["components/web-leads/BattleCard.tsx", /audit\.state === "parked"/],
  ["components/web-leads/WebsiteComparison.tsx", /audit\.state === "parked"/],
  // Re-aimed 2026-08-25, NOT relaxed. The results list grew a second layout
  // (cards below `xl`, table above), and its score renderer moved into
  // LeadCells.tsx so both layouts share one -- which is what keeps the phone
  // from saying something the desktop does not. This assertion follows the
  // renderer to where it actually lives; pointing it at LeadsTable.tsx now
  // would fail, and deleting it would leave the parked sentence unguarded on
  // every list surface at once.
  ["components/web-leads/LeadCells.tsx", /lead\.scoreState === "parked"/],
  ["components/manifest/LeadPipelineView.tsx", /m\.webScoreState === "parked"/],
] as const) {
  assert.match(read(file), needle, `${file} must render the parked state explicitly`);
}

console.log("parked-domains ok — a domain for sale is never a score and never a competitor");
