/**
 * The OpenNext build output worker-entry.ts wraps. It is generated by
 * `opennextjs-cloudflare build` and does not exist before a build, so its one
 * export used here is declared for the type checker.
 */
declare module "*/.open-next/worker.js" {
  const handler: {
    fetch(request: Request, env: unknown, ctx: unknown): Promise<Response>;
  };
  export default handler;
}
