/**
 * parked-domains — a domain that is FOR SALE is not a website.
 *
 * ═══ WHAT WENT WRONG, MEASURED 2026-08-25 ═══════════════════════════════════
 *
 * Adon, on a battle card for a Mississauga restaurant: two of the three
 * "best-scoring competitors" opened hugedomains.com, a page selling the domain,
 * not a restaurant.
 *
 * The links were the symptom. The real defect was the SCORE. Every one of the
 * 53 HugeDomains parking pages in the corpus scored **exactly 82**, and all 53
 * landed in the top tier (>=74, the band that "beats SunBiz, our best site").
 * That identical 82 is the tell: a parking page is one template, so it scores
 * once and that score repeats. And it scores WELL, because it is genuinely
 * fast, HTTPS, mobile-friendly, has a phone link, a form, testimonials and a
 * logo. Our 49 checks measure exactly those things. Nothing was broken; the
 * crawler faithfully measured a page that has nothing to do with the business.
 *
 * The consequence is the worst output this system can produce. Competitor
 * selection takes the BEST-scoring peers in a city and industry, so an 82
 * outranks almost every real site -- parked domains were not merely included,
 * they were PREFERENTIALLY surfaced. A rep on a live call would say "Ambiance
 * of India's site scores 82, yours scores 9" about a business that has no
 * website at all. That is a false statement to a prospect, in a rep's mouth,
 * generated by us.
 *
 * ═══ HOW IT IS DETECTED ═════════════════════════════════════════════════════
 *
 * `signals.finalUrl` was already being stored on every audit -- the URL after
 * redirects. Nothing read it. That is the whole detector, and it means this
 * works RETROACTIVELY on the 23,200 audits already in the corpus rather than
 * needing a re-crawl.
 *
 * Two rules, deliberately different in strength:
 *
 *   1. KNOWN PARKING HOSTS (high precision, acted on automatically). If a
 *      request for `ambianceofindia.com` ends at `hugedomains.com`, that is not
 *      their website by any reading. This list is the acted-on rule.
 *
 *   2. CROSS-DOMAIN REDIRECT (high recall, NOT acted on alone). Landing on a
 *      different registrable domain is suspicious but frequently legitimate: a
 *      rebrand, a franchise site, a Shopify or Wix storefront, a business whose
 *      whole web presence is a Facebook page. Disqualifying those would delete
 *      real competitors, which is the opposite failure. It is exposed for
 *      reporting so the list above can be GROWN from evidence rather than
 *      guesswork, and it is never used to drop a business on its own.
 *
 * The asymmetry is the point. Rule 1 removes a business from every score and
 * every peer group, so it must not be wrong. Rule 2 only ever produces a list
 * for a human to look at.
 */

/**
 * Hosts whose pages are domain sales, parking or expiry notices rather than a
 * business's website.
 *
 * Every entry earns its place by being a service whose ENTIRE purpose is
 * selling or parking a domain. A general host that merely *can* host a parking
 * page (a registrar that also does real hosting, a CDN) must never be added:
 * one wrong entry here silently deletes every business behind that host from
 * the corpus, and a shrinking peer group changes percentiles a rep quotes.
 */
export const PARKING_HOSTS: readonly string[] = [
  "hugedomains.com",
  "afternic.com",
  "sedo.com",
  "sedoparking.com",
  "dan.com",
  "undeveloped.com",
  "bodis.com",
  "parkingcrew.net",
  "above.com",
  "squadhelp.com",
  "buydomains.com",
  "domainmarket.com",
  "brandbucket.com",
];

/**
 * Markers that identify a parking page by its PATH rather than its host.
 *
 * Separate from PARKING_HOSTS because they are matched differently: a host is
 * compared against the parsed hostname on a label boundary, a path marker is a
 * substring of the whole URL. Mixing the two into one list is what produced the
 * false positive below.
 */
export const PARKING_PATH_MARKERS: readonly string[] = [
  "/domain_profile.cfm", // HugeDomains' own page
  "namesilo.com/parked",
];

/** The registrable-ish domain: last two labels, lowercased, `www.` dropped.
 *  Deliberately simple. It is used to compare two hosts to each other, not to
 *  make a security decision, and a public-suffix list would be a dependency for
 *  no gain here -- `co.uk` collapsing to `co.uk` compares equal on both sides. */
export function baseDomain(hostOrUrl: string | null | undefined): string | null {
  if (!hostOrUrl || typeof hostOrUrl !== "string") return null;
  let host = hostOrUrl.trim().toLowerCase();
  if (!host) return null;
  try {
    if (/^[a-z][a-z0-9+.-]*:\/\//.test(host)) host = new URL(host).hostname;
  } catch {
    return null;
  }
  host = host.replace(/^www\./, "").replace(/\.$/, "");
  if (!host) return null;
  const parts = host.split(".").filter(Boolean);
  if (parts.length <= 2) return host;
  return parts.slice(-2).join(".");
}

/**
 * RULE 1. Is this final URL a domain-sale or parking page?
 *
 * Substring match on the lowercased URL rather than host-only, because the
 * captured `finalUrl` is sometimes a full path and HugeDomains' own marker
 * (`domain_profile.cfm`) lives in the path. Fails CLOSED toward keeping the
 * business: an unparseable or missing finalUrl returns false, so a business is
 * only ever dropped on positive evidence.
 */
export function isParkedUrl(finalUrl: string | null | undefined): boolean {
  if (!finalUrl || typeof finalUrl !== "string") return false;
  const u = finalUrl.toLowerCase();

  // Path markers first: these identify the PAGE, wherever it is served from.
  if (PARKING_PATH_MARKERS.some((m) => u.includes(m))) return true;

  // ═══ HOST MATCHING IS ON A LABEL BOUNDARY, NOT A SUBSTRING ════════════════
  //
  // This was `PARKING_HOSTS.some((h) => u.includes(h))`, and it was wrong in
  // the one direction that costs us real businesses.
  //
  // Caught 2026-08-25 before any data was rewritten: "Chez Jordan Corporation"
  // at `https://www.chezjordan.com/` matched the entry `dan.com`, because
  // "chezjor|dan.com" contains it. A real restaurant with a real website
  // scoring 55 would have had its score stripped and been removed from every
  // peer group -- and a shrinking peer group moves the percentiles a rep quotes
  // out loud. `jordan.com`, `sudan.com` and `bogdan.com` are all the same trap.
  //
  // Comparing the parsed HOSTNAME, and requiring either an exact match or a
  // `.`-prefixed suffix, means only a genuine subdomain of a parking service
  // counts. Being wrong here in the permissive direction shows one bad
  // competitor; being wrong in the strict direction silently deletes good ones.
  const host = hostnameOf(u);
  if (!host) return false;
  return PARKING_HOSTS.some((h) => host === h || host.endsWith(`.${h}`));
}

/** The lowercased hostname, or null when the value is not a parseable URL.
 *  Deliberately does NOT strip `www.`: the boundary check below treats
 *  `www.dan.com` as a subdomain of `dan.com`, which is exactly right. */
function hostnameOf(value: string): string | null {
  try {
    const withScheme = /^[a-z][a-z0-9+.-]*:\/\//.test(value) ? value : `https://${value}`;
    return new URL(withScheme).hostname.toLowerCase() || null;
  } catch {
    return null;
  }
}

/**
 * RULE 2. Did the request end up on somebody else's domain?
 *
 * Reporting only. See the module header for why this must not drop a business
 * by itself: rebrands, franchises and hosted storefronts all redirect
 * cross-domain and are real websites.
 */
export function isCrossDomainRedirect(
  requestedUrl: string | null | undefined,
  finalUrl: string | null | undefined,
): boolean {
  const from = baseDomain(requestedUrl);
  const to = baseDomain(finalUrl);
  if (!from || !to) return false;
  return from !== to;
}

/** `signals` is stored as TEXT on the audit row and is sometimes already an
 *  object depending on the driver. Returns null rather than throwing, because a
 *  malformed signals blob must not take down a score index build. */
export function finalUrlFromSignals(signals: unknown): string | null {
  if (!signals) return null;
  let obj: unknown = signals;
  if (typeof signals === "string") {
    try {
      obj = JSON.parse(signals);
    } catch {
      return null;
    }
  }
  if (!obj || typeof obj !== "object") return null;
  const v = (obj as Record<string, unknown>).finalUrl;
  return typeof v === "string" && v.trim() ? v.trim() : null;
}

/** The SQL `or(...)` filter that finds parked audits without transferring 23,200
 *  signals blobs. Kept beside the list so the two cannot drift apart. */
export function parkedSignalsOrFilter(): string {
  return [...PARKING_HOSTS, ...PARKING_PATH_MARKERS]
    .map((h) => `signals.like.*${h}*`)
    .join(",");
}

/**
 * ═══ THE SQL FILTER IS A NET, NOT A VERDICT ═════════════════════════════════
 *
 * `signals.like.*dan.com*` matches `chezjordan.com`, and SQL LIKE cannot
 * express "on a hostname label boundary". So every row the query returns must
 * be re-checked here with `isParkedUrl`, which parses the hostname properly.
 *
 * Callers that use the query result directly are wrong in the expensive
 * direction: they strip the score from a real business and shrink the peer
 * group behind every percentile. This helper exists so there is one obvious
 * right way to consume that query.
 */
export function confirmParked(
  rows: { business_id: string; signals?: unknown }[],
): Set<string> {
  const parked = new Set<string>();
  for (const r of rows) {
    if (isParkedUrl(finalUrlFromSignals(r.signals))) parked.add(r.business_id);
  }
  return parked;
}
