/**
 * scripts/gen-og-card.ts - prebuild the marketing share card as a PNG module,
 * so the Worker serves fixed bytes instead of bundling an image renderer.
 *
 * WHY. app/(marketing)/opengraph-image.tsx used to return
 * `new ImageResponse(...)` from next/og on every request. On the Cloudflare
 * Worker that put @vercel/og into the upload (OpenNext includes it whenever a
 * route's file trace reaches it): the Satori library, resvg.wasm, yoga.wasm
 * and a fallback font, about 2 MiB of the 64 MiB limit, to draw one card that
 * has no inputs and so renders the same bytes every time.
 *
 * WHAT IT WRITES (committed): lib/marketing/og-card.generated.ts, the PNG that
 * lib/marketing/og-card.tsx renders, as one base64 string (pure ASCII, so it
 * cannot push the Worker source out of V8's one-byte form).
 *
 * tests/og-card-static.test.ts renders the card again and fails when the
 * committed module differs, so editing the design without running this script
 * fails CI instead of shipping a stale card.
 *
 * Usage:
 *   node --import tsx scripts/gen-og-card.ts          write the module
 *   node --import tsx scripts/gen-og-card.ts --check  exit 1 if it is stale
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import * as React from "react";

export const OG_CARD_MODULE = "lib/marketing/og-card.generated.ts";

const ROOT = path.join(__dirname, "..");

/** The module text for a rendered card. Deterministic: same bytes, same text. */
export function renderOgCardModule(png: Buffer): string {
  return (
    "// GENERATED by scripts/gen-og-card.ts. Do not edit by hand:\n" +
    "// edit lib/marketing/og-card.tsx and run `node --import tsx scripts/gen-og-card.ts`.\n" +
    "// tests/og-card-static.test.ts fails when this module differs from a fresh render.\n" +
    `// The marketing share card: PNG, ${png.length} bytes, base64.\n\n` +
    "export const OG_CARD_PNG_BASE64 =\n" +
    `  "${png.toString("base64")}";\n`
  );
}

/** Render the card with next/og, outside Next. */
export async function renderOgCardPngForModule(): Promise<Buffer> {
  // tsx compiles the card's JSX to React.createElement (tsconfig jsx: preserve).
  (globalThis as unknown as { React: typeof React }).React = React;
  const { renderOgCardPng } = await import("../lib/marketing/og-card");
  return renderOgCardPng();
}

async function main(): Promise<number> {
  const check = process.argv.includes("--check");
  const file = path.join(ROOT, OG_CARD_MODULE);
  const want = renderOgCardModule(await renderOgCardPngForModule());
  const have = existsSync(file) ? readFileSync(file, "utf8").replace(/\r\n?/g, "\n") : null;
  if (check) {
    if (have === want) return 0;
    console.error(`${OG_CARD_MODULE} is stale: run node --import tsx scripts/gen-og-card.ts`);
    return 1;
  }
  if (have !== want) writeFileSync(file, want);
  console.log(`${OG_CARD_MODULE}: ${have === want ? "unchanged" : "written"}`);
  return 0;
}

if (/gen-og-card\.ts$/.test(process.argv[1] || "")) {
  main().then(
    (code) => process.exit(code),
    (err) => {
      console.error(err);
      process.exit(1);
    },
  );
}
